= Enterprise Java goes Mobile
Oliver B. Fischer
2015-03-19 06:34:00 +0100
:jbake-event-date: 2015-05-18
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **18. Mai 2015** lädt die Java Usergroup Berlin-Brandenburg und die
http://www.votum.de[VOTUM GmbH]
zu den Vorträgen
**How to build Enterprise mobile apps that integrate with your Java EE backend**
und
**Successful Mobile Relationship management with Push Notifications**
mit **Matthias Wessendorf** und **Sébastien Blanc**
von https://www.redhat.com/[Red Hat] ein.

== Die Vorträge

**How to build Enterprise mobile apps that integrate with your Java EE backend**
(_Sébastien Blanc_):
Are you a Java developer and want to develop a mobile app that
connects to a secured Java EE backend, but you don't know where
to start? This session is tailored for you. This hands on session,
using a familiar development environment, goes step by step
through building a complete mobile, hybrid, multiplatform application.

Starting from scratch, the tutorial takes you through building a
simple Java EE application and, from there, scaffolding a
mutliplatform mobile client by using Cordova. Finally we will
show how to implement sending Push Notifications from the
backend to be received on the mobile client.

This is an in-depth session in which the attendees will learn
concretely, and without using hipster tools, how to enter
the mobile world.


**Successful Mobile Relationship management with Push Notifications**
(_Matthias Wessendorf_):
Business relationships take many forms like customers, partners
or employees. For mobile application development, managing these
relationships is crucial, since user interaction is an important
part of a successful mobile app. Push notifications, a key feature
of every mobile operating system, allow you to quickly reach your
mobile users. In this session, we’ll discuss how to send targeted
push messages from your Java backend including geolocation using
Hibernate and BPM or rules based notifications to your mobile users.

The UnifiedPush Server is an open source solution providing an
unified API for mobile operating systems, like iOS, Android or
Windows Mobile. Join us to learn why implementing push notifications
for several mobile platforms (each with its own proprietary API)
can be easier than you might think, whether your Java backends
are hosted in the cloud or inside your own datacenter.

== Die Redner

**Sébastien Blanc** is JEE engineer with 10 years of experience.
He works at Red Hat and focus on Open Source libraries for
Mobile in the Enterprise. He believes that Mobile Web/Hybrid
Apps are the future and tries to evangelize this through
different conferences (Devoxx, JUDCon, JavaOne, SpringOne).

**Matthias Wessendorf** 
(https://twitter.com/mwessendorf[@mwessendorf]) 
is the project lead of AeroGear,
working at Red Hat where he is focused on next generation of mobile
computing. Previously, he was the PMC Chair of the Apache MyFaces
project. Matthias is a regular conference speaker.

== Treffpunkt

VOTUM GmbH, Ohlauer Straße 43, 10999 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.

Die Veranstaltung wird in den nächsten Tagen nach
Ankündigung im JUG-Blog auf Meetup veröffentlicht.

