= Kryptokalypse now - Apache Tomcat aber sicher!
Oliver B. Fischer
2015-04-06 07:35:00 +0100
:jbake-event-date: 2015-04-20
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **20. April 2015** lädt die Java Usergroup Berlin-Brandenburg und die
http://www.immobilienscout24.de[Immobilien Scout GmbH]
zu dem Vortrag
**Kryptokalypse now - Apache Tomcat aber sicher!**
mit **Frank Pientka**
von http://www.materna.de/[MATERNA GmbH] ein.

== Der Vortrag

**Kryptokalypse now - Apache Tomcat aber sicher!** (_Frank Pientka_):
Sicherheit wird im Internet groß geschrieben. Trotzdem hat die Zahl
der Sicherheitslücken erschreckende Ausmaße angenommen. Am Beispiel
des weit verbreiteten Java-Webservers Apache Tomcat wird gezeigt,
welche Angriffsszenarien es gibt und was man dagegen tun kann.
Mit aktuellen Gefahrenpotentialen nach OWASP und CVE  werden
Lösungen mit Tomcat 8 und Java 8 diskutiert.  Mit wenigen
konsequent und regelmäßig durchgeführten Maßnahmen lässt sich
das Sicherheitsniveau erhöhen. Eine gute Möglichkeit sein Wissen
zum Thema Websicherheit und Verschlüsselung auf zu frischen
und sich auf Herausforderungen der Zukunft frühzeitig vorzubereiten.

== Der Redner

**Frank Pientka** arbeitet als Dipl.-Informatiker
(TH Karlsruhe) bei der MATERNA GmbH in Dortmund.
Als Software Architect sorgt er für mehr Qualität in der
Software und kümmert sich, als Gründungsmitglied des iSAQB,
um eine verbesserte Ausbildung und Zertifizierung von Architekten.
Seit mehr als zwei Jahrzehnten unterstützt er Firmen bei der
Umsetzung tragfähiger Software-Architekturen auf Basis von JavaEE.
Dabei führt er externe Reviews und Architekturbewertungen als
Gutachter durch. Dazu hat er auch schon mehrere Fachartikel
veröffentlicht und Vorträge gehalten.

== Treffpunkt

Immobilien Scout GmbH, Andreasstraße 10, 10243 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Vorabanmeldung zur Veranstaltung über das
XING-Event der
http://xing.to/jugbb/[XING-Gruppe der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.

