= Testcontainers -- Past, Present and Future
Oliver B. Fischer
2020-02-09 09:25:00 +0100
:jbake-event-date: 2020-02-25
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published



Am **Dienstag, den 25. Februar 2020**, lädt die
Java Usergroup Berlin-Brandenburg
und
https://www.lucanet.com/de/[LucaNet AG^]
zum Vortrag
**Testcontainers -- Past, Present and Future**
mit
https://twitter.com/bsideup?lang=de[Sergei Egorov^]
ein.

== Der Vortrag

**Testcontainers -- Past, Present and Future**
(_Sergei Egorov_):
Unit testing is fine, but without proper integration testing, especially if you
work with external resources like databases and other services, you might not
know how your application will actually behave once it has been deployed to the
real production environment.

Testcontainers is a popular JVM testing library that provides lightweight,
throwaway instances of common databases, Selenium web browsers, or anything else
that can run in a Docker container.

In this talk, we will briefly go throught the past, present and the future of
the library.

Spoiler! By coming, you may learn new things even if you're an active user of
Testcontainers ;-)

== Der Redner

**Sergei Egorov** works at Pivotal on Project Reactor in Berlin, Germany. He is an
active member of the Open Source community, member of the Apache Foundation,
co-maintainer of the Testcontainers project, and a contributor to various OSS
projects (Apache Groovy, Testcontainers, JBoss Modules, Spring Boot, to name a
few), likes to share the knowledge and was presenting at different conferences
and meetups in Russia, Germany, Ukraine, Norway, Denmark, Spain, and Estonia. He
is passionate about DevOps topics, clouds, and infrastructure. Before Pivotal,
he was working at Vivy, N26, Zalando, ZeroTurnaround, TransferWise, and other
startups.


== Treffpunkt


:hardbreaks:

LucaNet AG
Alexanderplatz 1
10178 Berlin
Germany

:!hardbreaks:

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.





