= Think beyond the GUI
Oliver B. Fischer
2020-01-06 22:45:00 +0100
:jbake-event-date: 2020-03-04
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published




Am **Mittwoch, den 4. März 2020**, lädt die
Java Usergroup Berlin-Brandenburg
und
https://www.innoq.com[INNOQ^]
zum Vortrag
**Think beyond the GUI**
mit
https://twitter.com/wuschey[Aminata Sidibe^]
ein.

== Der Vortrag

**Think beyond the GUI**
(_Aminata Sidibe_):
Wir brauchen dafür eine (Web)App" – Diese und ähnliche Sätze fallen sehr häufig,
wenn es um die Entwicklung digitaler Produkte und Services geht. Es passiert
sehr schnell, dass wir in konkrete und schon bestehende Lösungsszenarien denken
und unsere Architekturen somit automatisch auf diesen Szenarien aufbauen.

Durch die Allzweck-Waffe Smartphone sind wir es mittlerweile gewohnt, fast alles
auf einen Display zu bringen, was in unseren Köpfen in Form einer Idee schwebt –
Ohne vielleicht einen Schritt zurück zu gehen um uns über den Nutzer in seinem
konkreten Kontext Gedanken zu machen. Ist eine angepriesene smarte Lösung zum
Beispiel wirklich immer smart?!

Oft kann ein GUI sogar den Nutzer eher stören, als dass es ein konkretes Problem
löst. Wie sinnvoll ist es also seine Produktideen direkt als Bedienelement zu
denken? Gibt es in der heutigen Zeit nicht Alternativen, mit denen wir den
Menschen, der hinter der Benutzung steht, sinnvoller unterstützen können, als
mit grafischen User Interaces?

In meinem Talk möchte ich über die Probleme von grafischen UserInterfaces
sprechen, um gleichzeitig zu alternativen Denkansätze zu inspirieren. Die
Auswirkungen auf die tägliche Architekturarbeit möchte ich auch gerne in der
Runde diskutieren.

== Die Rednerin

**Aminata Sidibe** ist Principal Consultant bei INNOQ. Sie beschäftigt sich seit
vielen Jahren mit der Umsetzung komplexer Applikationen und eCommerce-Projekte.
Ihr Fokus liegt auf der Mensch-Maschinen-Interaktion. (GUIs, Voice UIs, Smart
Home, ...). +
Themen im Bereich der User Experience gehören neben der Technologie
zu ihrer täglichen Arbeit


== Treffpunkt

:hardbreaks:

https://www.google.de/maps/place/innoQ+Deutschland+GmbH/@52.49403,13.427006,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84fb457ec5c5b:0xa406bef9bec3c42[innoQ Deutschland GmbH,
Ohlauer Str. 43,
Treppenhaus C, 2. OG,
10999 Berlin^]

:!hardbreaks:

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.





