= Graph Databases with Neo4j and Cypher
Oliver B. Fischer
2013-08-07
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

// @todo &#038; anstatt and im Titel

Am **20. August 2013** lädt die Java Usergroup Berlin-Brandenburg und die
http://www.groupon.de/[Groupon GmbH] zum  Vortrag
**Graph Databases with Neo4j &#038; Cypher** mit **Stefan Plantikow** ein.


== Der Vortrag


**Graph Databases with Neo4j &#038; Cypher** (_Stefan Plantikow_): Graph databases
are everywhere. From social netwoks, to access control and content management
systems, graph databases are a new class of general purpose databases from the
NoSQL world for storing and processing large data sets of heavily interconnected
data. This talk will give an overview on graph databases and Neo4j with a focus on
how to use them in a Java environment. We will look at how graph databases are
well suited for modelling rapidly changing problem domains, how to query Neo4j
using the declarative graph query language Cypher, and at large scale graph
database use cases. To conclude, we will take a look at new features in the
upcoming version Neo4j 2.0.


==  Der Redner

**Stefan Plantikow** is a computer scientist with a background in distributed
and concurrent systems and transaction processing. He is passionate about
computer language design and how languages influence software development.
Based in Germany as an independent consultant, he's currently working on the
next version of Neo4j. He also presents graph technology at NoSQL and
other events. Stefan enjoys traveling, skiing, and tai chi.

== Der Treffpunkt

Groupon GmbH, Oberwallstraße 6, 10117 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit zu Networking und Plausch.

== Die Anmeldung

Über eine Vorabanmeldung zur Veranstaltung über das XING-Event der
https://www.xing.com/net/pri047e5ex/jugbb/[XING-Gruppe der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.



