= Verteiltes Suchen mit ElasticSearch
Oliver B. Fischer
2013-05-23 00:00:00 +0100
:jbake-event-date: 2013-06-11
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **11. Juni 2013** lädt die Java Usergroup Berlin-Brandenburg und die
http://www.groupon.de/[Groupon GmbH] zu dem Vortrag
**Verteiltes Suchen mit ElasticSearch** mit **Dr. Halil-Cem Gürsoy**
von der http://www.adesso.de/de/[adesso AG] ein.


== Der Vortrag

**Verteiltes Suchen mit ElasticSearch** (_Dr. Halil-Cem Gürsoy_):
Mit Elasticsearch existiert eine auf Apache Lucene basierende Suchmaschine,
die auf eine Anwendung in großen verteilten Systemen  optimiert sein möchte.
Hierdurch bietet sie sich insbesondere für  Cloud-Szenarien an.
In dieser Session erfolgt eine Einführung in diese schemalose und
dokumentenorientierte Suchengine, die auf REsT und JSON setzt.
Dabei werden auch fortgeschrittene Aspekte wie Sharding
oder Routing betrachtet.

== Der Redner

**Dr. Halil-Cem Gürsoy** ist als Software Architect bei der
adesso AG in Dortmund tätig. Sein technologischer Schwerpunkt
liegt dabei auf Java Enterprise (JEE, Spring). Er fokusiert
sich aktuell auf verteilte Applikationen, vorzugsweise in der Cloud,
sowie die Herausforderungen, die im Zusammenhang mit der Persistenz in
solchen Applikationen einhergehen.


== Treffpunkt

Groupon GmbH, Oberwallstraße 6, 10117 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß und Zeit zum Networking
- 19:00 Uhr Vortragsbeginn

== Die Anmeldung

Über eine Voranmeldung zur Veranstaltung über das
XING-Event der
https://www.xing.com/net/pri4a51a0x/jugbb/[XING-Gruppe der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
