= Amazon Webservices for Java Developers
Oliver B. Fischer
2012-01-10 00:00:00 +0100
:jbake-event-date: 2012-01-24
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **24. Januar 2012** lädt die Java Usergroup Berlin-Brandenburg zusammen mit
der http://www.adesso.de/de/[adesso AG^] zum  Vortrag
**Amazon Webservices for Java Developers** mit
**Jan Borch** von Amazon AWS ein.

== Die Vorträge

**Amazon Webservices for Java Developers &#8211; Part 1** (_Jan Borch_):
Beanstalk, Cloud Formation, EC2, ElasticCache, SimpleDB, RDS, ELB, and
more. Overview on how to leverage AWS services for Continuous
Integration/Deployment/Optimization

**Amazon Webservices for Java Developers &#8211; Part 2** (_Jan Borch_):
Overview of the AWS tools for Java developer : Java AWS SDK, AWS eclipse plugin,
and more. Bootstrapping Application with CloudFormation and integration
with Chef and Puppet.


== Der Redner

**Jan Borch** ist Solution Architect im Amazon AWS EMEA Solution
Architect team.

== Der Treffpunkt

GLS Campus, Haus 3, Aula, Kastanienallee 82, 10435 Berlin (Prenzlauer Berg)

== Hinweis

Die Anfangsuhrzeit kann sich ggf. noch verändern, sollte aber bis
13. Januar feststehen.

== Der Ablauf

- 17:00 Uhr Einlaß und Zeit für Networking
- 17:30 Uhr Vortragsbegin (ca. 2 bis 2,5 Stunden)


== Die Anmeldung

Die Anmeldung zur Veranstaltung erfolgt über das
https://www.xing.com/net/pri047e5ex/jugbb/[XING-Event der
XING-Gruppe der JUG Berlin-Brandenburg].



