= JPA als Standard und die Optimierung von JPA-Anwendungen
Oliver B. Fischer
2012-12-16 00:00:00 +0100
:jbake-event-date: 2013-01-31
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published



Am **31. Januar 2013** lädt die Java Usergroup Berlin-Brandenburg zum Vortragsabend
**JPA als Standard und die Optimierung von JPA-Anwendungen** ein.

== Die Vorträge

**JPA – Der Persistenz-Standard in der Java EE und SE** (_Michael Bouschen_):
Die Abbildung relationaler Strukturen einer Datenbank auf die objekt-orientierte
Programmiersprache Java bringt einige Herausforderungen mit sich, bekannt
als _object-relational impedance mismatch_. In Java ermöglicht JDBC zwar die
Interaktion mit einer relationalen Datenbank, aber nicht die Abbildung der Daten
auf Objekte. Die bekannten Produkte wie Hibernate oder EclipseLink widmen sich
diesem Problem bereits seit Jahren. Mit JPA hat der Java Community Process
einen Standard für Java EE und SE definiert, der ein einheitliches API bietet,
welches von den Anbietern unterstützt wird. Der Vortrag zeigt was JPA bietet
und welche Vorteile der Standard für die Anwendungsentwicklung mit sich bringt.


**Optimierung von JPA-Anwendungen** (_Dirk Weil_):
War Persistenz in Java EE früher schwergewichtig und unflexibel, so steht nun
der leichtgewichtige Standard JPA mit Providern wie EclipseLink und Hibernate
zur Verfügung. Die Einfachheit ist bestechend, verleitet aber auch zu
unbedachtem Einsatz mit teilweise enttäuschender Performanz. Der Vortrag
zeigt wie JPA-Anwendungen auf den nötigen Durchsatz hin optimiert werden können.

== Die Redner

**Michael Bouschen** ist Software Architekt bei http://www.akquinet.de/[akquinet^] und
leitet eine Reihe von großen Entwicklungsprojekten im Java Enterprise Bereich
für namhafte Kunden. Er hat einen langjährigen Erfahrungshintergrund in Java.
Sein Focus liegt auf der Java Persistenz und Michael ist aktives Mitglied
der JCP Expertengruppen für Java Persistence API (JPA) und Java Data Objects (JDO).
Außerdem ist er ein Mitglied des Apache DB Projekt Management Committee (PMC)
und Committer im Apache JDO Projekt.

**Dirk Weil** ist Fachbereichsleiter Java bei
http://www.ips-it-schulungen.de/[IPS Institut für Personalschulung GmbH^]
und Geschäftsführer der http://www.gedoplan.de/[GEDOPLAN GmbH^] in Bielefeld.
Er ist seit 1998 als Berater im Bereich Java und Java EE tätig und arbeitet mit
JBoss, GlassFish, Weblogic und NetWeaver. Er ist Autor des
Java Magazins, hält Vorträge und leitet Seminare zu zahlreichen Themen.

== Der Treffpunkt

FU Berlin, Hörsaal der Informatik, Takustrasse 9, 14195 Berlin


== Der Ablauf

- 18:30 Uhr Einlaß und Zeit zum Networking
- 19:00 Uhr Vortragsbeginn


== Die Anmeldung

Über eine Vorabanmeldung zur Veranstaltung über das
https://www.xing.com/net/pri047e5ex/jugbb/[XING-Event der XING-Gruppe
der JUG Berlin-Brandenburg^]  würden wir uns freuen, jedoch ist die
Anmeldung nicht zwingend erforderlich. Wir freuen uns auf jeden Teilnehmer.


