= Securing Internet Services with OAuth 2.0
Oliver B. Fischer
2012-03-12 00:00:00 +0100
:jbake-event-date: 2012-04-04
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **4. April 2012** lädt http://www.gameduell.de/[GAME:DUELL^]
und die Java Usergroup Berlin-Brandenburg zum Tech Talk
**Securing Internet Services with OAuth 2.0** mit
**Dr. Torsten Lodderstedt** ein.

== Der Vortrag

**Securing Internet Services with OAuth 2.0** (_Dr. Torsten Lodderstedt_):
Ein Internet-Produkt muss Kunden heute mehr bieten als den Zugriff auf
ihre Inhalte über eine Webseite. Apps für verschiedene Smartphone-Plattformen
sind selbstverständlich und am besten können die Kunden ihre Inhalte, wie
bei Facebook, auch aus anderen Angeboten heraus nutzen. Diese Anforderungen
werden heute typischerweise durch die Bereitstellung eines HTTP-basierten
APIs erfüllt, das den Zugriff aus eigenen und den Anwendungen Dritter auf
die Inhalte der Kunden erlaubt. Hierbei ist eine Kernfrage: Wie sichert man
ein solches API gegen Missbrauch ab, ohne Kunden und Entwickler unnötig zu
behindern? Das Autorisierungsprotokoll OAuth 2.0 bietet hierfür passenden
Antworten und ist einfach zu verwenden, gute Gründe warum Branchengrößen
wie Google und Facebook auf OAuth setzen. Der Vortrag wird das Protokoll
vorstellen und Hinweise geben, was bei dessen Implementierung zu beachten
ist.

== Der Redner

**Dr. Torsten Lodderstedt** ist Product Owner für Identitäts- und
Kunden-Management bei der Deutschen Telekom. Er arbeitet in der
OAuth Arbeitsgruppe der IETF an der Spezifikation des Protokolls,
seine Schwerpunkte sind hierbei mobile Apps und Sicherheit. Er bringt
dort die Erfahrungen der Deutschen Telekom bei der Implementierung
von Diensten für das Identity Management ein.

== Der Ablauf

- 18:30 Uhr: Einlass
- 19:00 Uhr: Vortrag Torsten Lodderstedt
- 20:00 Uhr: Diskussionsrunde
- 20:30 Uhr: Get Together mit Bier und Snacks

== Die Anmeldung

Bei Interesse schickt bitte eine Mail mit Eurem Namen an
mailto:Franziska.Holtz@gameduell.com[Franziska.Holtz@gameduell.com].
Daraufhin geben wir Euch den Veranstaltungsort in Berlin bekannt und
tragen Euch in die Gästeliste ein.

Die Anmeldung zur Veranstaltung kann auch alternativ über das dafür
erstellte XING-Event erfolgen: https://www.xing.com/events/einladung-event-tech-talk-securing-internet-services-with-oauth-2-0-891189[XING-Event Event Tech Talk: Securing Internet Services with OAuth 2.0^].



