= JDK 9 und die modulare Plattform Jigsaw
Oliver B. Fischer
2016-03-20 18:50:00 +0100
:jbake-event-date: 2016-04-12
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **12. April 2016** lädt die Java Usergroup Berlin-Brandenburg
und die http://www.hypoport.ag/[Hypoport AG] zum Vortrag
**JDK 9 und die modulare Plattform Jigsaw** mit **Wolfgang Weigend**
von der
http://www.oracle.com/de/index.html[Oracle Deutschland B.V. & Co. KG]
ein.

== Der Vortrag

**JDK 9 und die modulare Plattform Jigsaw**
(_Wolfgang Weigend_):
Im vergangenen Dezember wurde der Feature-Complete-Status für JDK 9
mit der neuen Plattformmodularisierung im Projekt Jigsaw auf den
26. Mai 2016 verlegt. Über die JDK-Enhancement-Vorschläge
JEP 200 (Modulares JDK), JEP 201 (Modularer Source-Code) und
JEP 220 (Modulare Laufzeit-Images) gelangen die technischen
Vorschläge ins JDK 9. Diese Veränderungen lassen es zu, mit dem
JDK 9 die gewünschte technische Paketierung von ausgewählter
Java-Funktionalität selbst zu bestimmen. Das Projekt Jigsaw hat
die primäre Aufgabe, das Design und die Implementierung eines
Standard-Modulsystems für die Java-Plattform und für das
JDK 9 bereitzustellen. Dabei soll die durchgängige, dynamische
und einfache Anpassbarkeit der Java-SE-Plattform & dem JDK, auch
für kleine Endgeräte berücksichtigt werden, sowie die Verbesserung
von Sicherheit und Wartbarkeit von
Java-SE-Plattform-Implementierungen, speziell vom JDK, verwirklicht
werden. Die geplante Verfügbarkeit vom JDK 9 ist für Ende März 2017
vorgesehen.

== Der Redner

**Wolfgang Weigend** ist Systemberater für Oracle Fusion Middleware
bei der Oracle Deutschland B.V. & Co. KG und zuständig für Java-Technologie
und -Architektur in der Entwickler-Community, sowie dem Einsatz bei Kunden
und Partnern, verfügt über langjährige Erfahrung in der Systemberatung und
im Bereich objektorientierter Software-Entwicklung mit Java.

== Treffpunkt

Hypoport AG, Klosterstr. 71, 10179 Berlin


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Vorabanmeldung Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
