= The Lagom Framework
Oliver B. Fischer
2016-04-20 21:12:00 +0100
:jbake-event-date: 2016-05-02
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **2. Mai 2016** lädt die Java Usergroup Berlin-Brandenburg
und die http://www.innoq.com[InnQ Deutschland GmbH^]
zum Vortrag **The Lagom Framework** ein.

== Die Vorträge

**The Lagom Framework** (_Lutz Huehnken_):
http://www.lagomframework.com/[Lagom^] is an open source JVM
microservice framework from Lightbend (the makers of Akka and
Play). It's been designed from the ground up for doing just
that - building microservices.

But not only that, the creators describe it as being
"highly opinionated". The natural question is, then -
what are those opinions, exactly? We will explore them,
and the related concepts:
- Use context bounds as boundaries for services! (Domain Driven Design)
- The event log is the book of record! (Event Sourcing)
- Separate the read and write sides! (CQRS)
- Microservices, too, need to be elastic and resilient! (Reactive)
- Developer experience matters! (The Lagom development setup)

At the end, you should have a good understanding of why things
in Lagom are the way they are, and what to expect if
you decide to build microservices with it.


== Der Redner

**Lutz Huehnken** is a Solutions Architect at Lightbend. He's
been working in professional software development since 1997,
and has successfully deployed major web applications for
clients in different fields (retail, logistics, hospitality,
finance). His current focus in on the development of reactive
applications - responsive, scalable, resilient systems -
with Scala, Akka and Play. Occasionally he speaks about
this at conferences. Online he can be found at http://www.huehnken.de/[^].

== Treffpunkt

https://www.google.de/maps/place/innoQ+Deutschland+GmbH/@52.49403,13.427006,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84fb457ec5c5b:0xa406bef9bec3c42[innoQ Deutschland GmbH, Ohlauer Str. 43, Treppenhaus C, 2. OG, 10999 Berlin^]

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
