= Nighthacking Tour Germany in Berlin
Oliver B. Fischer
2016-02-25 22:49:00 +0100
:jbake-event-date: 2016-03-03
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **3. März 2016** lädt die Java Usergroup Berlin-Brandenburg
und die http://immobilienscout24.de/[Immobilien Scout GmbH^]
zur **http://nighthacking.com/[Nighthacking Tour^]** mit
http://steveonjava.com/[Steve Chin (Steve on Java), Lead Java Community Manager bei Oracle]
und Sebastian Daschner, IT-Berater, ein. Die Veranstaltung wird live
via http://nighthacking.com/[^] gestreamt.


== Die Vorträge

**Raspberry Pi with Java** (_Stephen Chin_):
In this session I will walk you through how to build your own retro handheld
console that is powered by Java, runs on a Raspberry Pi, and is printed on a
3D printer.  Some of the topics that we will cover along the journey include:

- Hacking Java on the Raspberry Pi
- Rigging input devices with Pi4J
- Insane performance tuning on the JVM
- Why your boss [or SO] needs to buy you a 3D printer!

And of course your retro gaming mettle will be put to the test, so make sure to
dust off your old 8 and 16 bit consoles to prepare.

This presentation is about the most fun you can have while still legitimately calling
this conference “work.”  In fact, I will hopefully inspire you to do your own
creative “work” leveraging Java and Raspberry Pi to hack the real world.

**Putting Hypermedia Back in REST with JAX-RS** (_Sebastian Daschner_):
Everybody is doing REST -- at least everybody claims they are. But mostly web APIs
are built without Hypermedia, what would allow the client to follow
related resources and autonomously navigate through the API without
prior implicit logic of the application. This sessions shows the concept
and benefits of a Hypermedia driven REST API and how to
implement this using JavaEE 7 with JAX-RS.

In this session I will give an introduction for RESTful web services
with Hypermedia as the engine of application state, what the benefits
and costs of using this approach are and show different approaches
how to realize such REST services with JavaEE 7 and JAX-RS.
Most of the time will be spend demonstrating different implementations (
plain JavaEE 7, existing libraries, etc.) with live coding.
The session is held in English.


== Die Redner

**Stephen Chin** is the Lead Java Community Manager at Oracle, author of Raspberry
Pi with Java, co-author of Pro JavaFX Platform, and JavaOne Community Chair.
He has keynoted numerous Java conferences around the world including JavaOne,
where he is a 5 time Rock Star Award recipient. Stephen is an avid motorcyclist
who has done several Pan-European evangelism tours, interviewing hackers in their
natural habitat and posting the videos on http://nighthacking.com/[^]. When he is
not traveling, he enjoys teaching kids how to do embedded and robot
programming together with his 13 year old daughter.

**Sebastian Daschner** is a Java freelancer working as a Consultant,
Software Developer, and Architect and is enthusiastic about programming
and Java (EE). He is an JCP member, participating in the JSR processes
and hacking on various open source projects on Github. He has been
working with Java for more than 5 years. Besides Java, Sebastian is
also a heavy user of Linux and container technologies like Docker.
He evangelizes computer science practices on
https://blog.sebastian-daschner.com[^]
and on Twitter via http://twitter.com/DaschnerS[@DaschnerS^].


== Treffpunkt

Immobilien Scout GmbH,
Andreasstr. 10,
10243 Berlin


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
