= Self-contained Systems: Microservices-Architekturen mit System
Oliver B. Fischer
2016-11-20 19:26:00 +0100
:jbake-event-date: 2016-12-07
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **7. Dezember 2016** lädt die Java Usergroup Berlin-Brandenburg
und die http://www.innoq.de/[InnoQ GmbH^] zum Vortrag
**Self-contained Systems: Microservices-Architekturen mit System** mit
**Eberhard Wolff** ein.

== Der Vortrag

**Self-contained Systems: Microservices-Architekturen mit System**
(_Eberhard Wolff_):
Self-contained Systems (http:///scs-architecture.org[SCS^]) nutzen die
Ideen von Microservices und teilen Systeme in stark entkoppelte
Anwendungen auf. So können große, komplexe Anwendungen strukturiert
werden - aber auch in vielen anderen Szenarien sind die Ansätze sinnvoll
nutzbar. SCS werden bei Firmen wie Otto, Kaufhof oder Kühne+Nagel
erfolgreich eingesetzt. Der Workshop erklärt zunächst SCS und zeigt die
Unterschiede zu Microservices sowie am praktischen Beispiel technische
Aspekte wie Frontend-Integration. Schließlich entwerfen wir eine
technische und fachliche Architektur für ein SCS-System.

== Der Redner

**Eberhard Wolff** ist Fellow bei innoQ und arbeitet seit mehr als fünfzehn
Jahren als Architekt und Berater, oft an der Schnittstelle zwischen
Business und Technologie. Er ist Autor zahlreicher Artikel und Bücher,
u.a. zu Continuous Delivery und Microservices und trägt regelmäßig als
Sprecher auf internationalen Konferenz vor. Sein technologischer
Schwerpunkt sind moderne Architektur- und Entwicklungsansätze wie Cloud,
Continuous Delivery, DevOps, Microservices und NoSQL.

== Treffpunkt

https://www.google.de/maps/place/innoQ+Deutschland+GmbH/@52.49403,13.427006,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84fb457ec5c5b:0xa406bef9bec3c42[innoQ Deutschland GmbH, Ohlauer Str. 43, Treppenhaus C, 2. OG, 10999 Berlin^]


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Vorabanmeldung Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
