= Self-contained Systems: Microservices-Architekturen mit System
Oliver B. Fischer
2016-11-20 19:26:00 +0100
:jbake-event-date: 2016-12-07
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **7. Dezember 2016** lädt die Java Usergroup Berlin-Brandenburg
und die http://www.innoq.de/[InnoQ GmbH^] zum Vortrag
**Self-contained Systems: Microservices-Architekturen mit System** mit
**Eberhard Wolff** ein.

== Der Vortrag

**Self-contained Systems: Microservices-Architekturen mit System**
(_Eberhard Wolff_):
Microservices sind der aktuelle Hype in der Software-Architektur-Szene.
Aber einfach nur kleine Dienste entwickeln, ist bei weiterm nicht genug.
Self-contained Systems (http:///scs-architecture.org[SSC^]) fokussieren
auf einen Architektur-Ansatz, der nicht nur bei großen Systemen mit
entsprechend komplexer Team-Struktur sinnvoll ist. Mit SCS kann in einem
solchen Kontext auch langfristig produktiv Software entwickelt
werden. Der Vortrag erläutert Self-contained Systems, ihre Vor- und
Nachteile und die Abgrenzung zu Microservices.

== Der Redner

**Eberhard Wolff** ist Fellow bei innoQ und arbeitet seit mehr als fünfzehn
Jahren als Architekt und Berater, oft an der Schnittstelle zwischen
Business und Technologie. Er ist Autor zahlreicher Artikel und Bücher,
u.a. zu Continuous Delivery und Microservices und trägt regelmäßig als
Sprecher auf internationalen Konferenz vor. Sein technologischer
Schwerpunkt sind moderne Architektur- und Entwicklungsansätze wie Cloud,
Continuous Delivery, DevOps, Microservices und NoSQL.

== Treffpunkt

https://www.google.de/maps/place/innoQ+Deutschland+GmbH/@52.49403,13.427006,17z/data=!3m1!4b1!4m2!3m1!1s0x47a84fb457ec5c5b:0xa406bef9bec3c42[innoQ Deutschland GmbH, Ohlauer Str. 43, Treppenhaus C, 2. OG, 10999 Berlin^]


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.
