= Java 8 Streams
Oliver B. Fischer
2014-05-18 12:19:28 +0200
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **4. Juni 2014** lädt die Java Usergroup Berlin-Brandenburg und die
http://www.hypoport.ag/[Hypoport AG] zu dem Vortrag
**Java 8 Streams**
mit **Sven Ruppert**
ein.

## Der Vortrag

**Java 8 Streams**
(*Sven Ruppert*):
Java 8 bringt einige Neuerungen mit sich. Eine der
größeren Veränderungen ist die Einführung der neuen
Streams-API in Verbindung mit Lambdas.
Zusammen ergeben diese beiden Dinge sehr effektive
Werkzeuge für den Entwickler. Wir schauen uns an, was
genau diese Streams sind, wie man sie einsetzen kann
und welche Vorteile sich aus dem Einsatz ergeben. Beispiele
aus dem Bereich der Nebenläufigkeit und der Integration in
JavaFX zeigen auf, wie Streams in der täglichen Arbeit eingesetzt
werden können. Zum Schluss werden wir uns damit auseinandersetzen
wie pre JDK8 Designpatterns migriert werden können.

## Der Redner

Sven Ruppert arbeitet als Principal IT Consultant bei der
codecentric in München, spricht seit 1996 Java und arbeitet
seitdem in nationalen und internationalen Projekten. In
seiner Freizeit schreibt er als 
http://jaxenter.de/Sven-Ruppert-168244[Gastautor für Jaxenter]
sowie im Java-, Entwickler- und EclipseMagazin.
Am liebsten jedoch hält er in 
http://tinyurl.com/nmtu4yv[Deutschland bei JUG Vorträge].

## Treffpunkt 

Hypoport AG, Klosterstr. 71, 10179 Berlin

## Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

## Die Anmeldung

Über eine Voranmeldung zur Veranstaltung über das
XING-Event der 
https://www.xing.com/net/pri4a51a0x/jugbb/[XING-Gruppe der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend 
erforderlich. Wir freuen uns auf jeden Teilnehmer.




