= Extrem produktive Webentwicklung mit dem Ninja Web Framework
Oliver B. Fischer
2014-11-15 14:54:15 +0100
:jbake-event-date: 2014-12-04
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **4. Dezember 2014** lädt die Java Usergroup Berlin-Brandenburg und die 
http://www.votum.de[Votum GmbH] zu dem Vortrag
**Extrem produktive Webentwicklung mit dem Ninja Web Framework**
mit 
**Raphael André Bauer**
ein.

== Der Vortrag

**Extrem produktive Webentwicklung mit dem Ninja Web Framework** 
(_Raphael André Bauer_): In 
den letzten Jahren hat sich die Art und Weise wie Webanwendungen
entwickelt werden dramatisch verändert.  Der einst allgegenwärtige
Monolith wird Stück für Stück durch agile Microservices ersetzt. Der
Trend zu DevOps Teams ist ungebrochen. Durch diesen Wandel haben sich
die Anforderungen an Web Frameworks stark verändert.

Ninja ist die Java Antwort auf diese neuen Herausforderungen: Ein
modernes, stateless, restful MVC Web Framework. Im Gegensatz zu vielen
anderen Frameworks bietet Ninja nicht nur Unterstützung bei der reinen
Entwicklung sondern auch während dem Deployment und Livebetrieb. Ninja
ist von Java Entwicklern für Java Entwickler geschrieben.

Schwerpunkte des Vortrags:

  - Erstellung einer Ninja Anwendung in Sekunden
  - Produktivität für Entwickler: SuperDevMode und komfortable IDE Unterstützung.
  - Struktur einer Ninja Anwendung: Restful Routen, Html, Json und Xml rendering
  - Inversion of Control, Testbarkeit und Continuous Integration Systeme
  - Stateless Deployment und Skalierbarkeit (war, fat jar, App Engine…)
  - Monitoring und Maintenance im Livebetrieb

Mehr über Ninja: http://ninjaframework.org

== Der Redner

**Raphael André Bauer** arbeitet als freiberuflicher IT Consultant 
mit internationalen
Firmen wie Holtzbrinck, Macmillan und Springer Science. Darüber hinaus
ist er an verschiedenen Berliner Startups beteiligt und aktiver
Contributor verschiedener Open Source Projekte.
Mehr Informationen gibt es unter http://raphaelbauer.com/

== Treffpunkt 

VOTUM GmbH, Ohlauer Straße 43, 10999 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zur Veranstaltung über das
XING-Event der 
http://xing.to/jugbb[XING-Gruppe der JUG Berlin-Brandenburg]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend 
erforderlich. Wir freuen uns auf jeden Teilnehmer.


