= Aktuelle und zukünftige Versionen vom Oracle JDK und OpenJDK
Oliver B. Fischer
2018-04-15 20:03:00 +0100
:jbake-event-date: 2018-05-16
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published




Am **Mittwoch, den 16. Mai 2018** lädt die
Java Usergroup Berlin-Brandenburg zusammen mit der
https://www.adesso.de/de/[adesso AG^] zum Vortrag
**Aktuelle und zukünftige Versionen vom Oracle JDK & OpenJDK**
mit Wolfgang Weigend von
http://www.oracle.com/[Oracle Deutschland] ein.

== Der Vortrag

**Aktuelle und zukünftige Versionen vom Oracle JDK & OpenJDK**
(_Wolfgang Weigend_):
Mit dem neuen JDK-Enhancement-Proposal (JEP 322), wird die zeitbasierte
Java-Release-Versionierung definiert, die auf dem neuen Java SE
Version-String-Schema basiert und die Namensgebung für die kommenden
Versionen der Java SE Plattform und vom JDK vorgibt. Die künftigen
Java-Releases erscheinen ab dem Jahr 2018 alle 6 Monate als Feature-Release.
Mit dem zeitlichen Abstand von sechs Monaten bekommen die Entwickler wesentlich
schneller neue Java-Funktionsmerkmale als dies mit dem bisherigen
Dreijahreszyklus der Fall war. Zwischen den JDK-Feature-Releases sind
zwei Updates geplant, bei denen es um die Wartung und Bugfixes geht,
die wie gewohnt, jeweils im Januar, April, Juli und Oktober eines
Jahres als Java Critical Patch Update erscheinen werden. Die Planung
sieht vor, jeweils alle drei Jahre ein weiteres Java-LTS-Release zu
veröffentlichen, damit der Anwendungsbetrieb eine stabile und ausgereifte
Java-Basis bekommt, die mit der nachfolgenden Versionierung
$FEATURE.$INTERIM.$UPDATE.$PATCH gekennzeichnet wird. Das JDK 10
wurde im März dieses Jahres als aktuelles Feature-Release veröffentlicht.
Nach sechs Monaten folgt im September 2018 das JDK 11 als
Long-Term-Support-Release (LTS-Release), welches über den
Zeitraum von fünf Jahren weitere Java Updates für die Nutzer
mit Java SE Advanced Support zugänglich macht. Im Vortrag werden
die Unterschiede vom Oracle JDK zum OpenJDK besprochen, sowie
Empfehlungen diskutiert, wie die künftige Java-Strategie mit Java
SE Advanced Support für die Entwickler und für den Anwendungsbetrieb
aussehen soll.

== Der Redner

**Wolfgang Weigend** ist Systemberater für Oracle Fusion Middleware
bei der Oracle Deutschland B.V. & Co. KG und zuständig für Java-Technologie
und -Architektur in der Entwickler-Community, sowie dem Einsatz bei Kunden
und Partnern, verfügt über langjährige Erfahrung in der Systemberatung und
im Bereich objektorientierter Software-Entwicklung mit Java.


== Treffpunkt

adesso AG, Rotherstr. 19, 10245 Berlin


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.

