= Mit Schema-Validierung APIs lahmlegen
Oliver B. Fischer
2018-09-23 19:17:00 +0100
:jbake-event-date: 2018-10-15
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **Montag, den 15. Oktober 2018** lädt die
Java Usergroup Berlin-Brandenburg zusammen mit der
https://www.codecentric.de/karriere/[codecentric AG^]
zum Vortrag
**Mit Schema-Validierung APIs lahmlegen**
mit Peter Liske, Senior Software Developer bei
Zalando, ein.

== Der Vortrag

**Mit Schema-Validierung APIs lahmlegen**
(_Peter Liske_): Das "JSON-Schema Specification Draft" ist der
aktuelle Standard zur Verifizierung von JSON-Datenstrukturen. Leider
enthält die Spezifikation eine Schwachstelle, mit der man eine
Applikation komplett blockieren kann. In meinem Vortrag zeige
ich, wie man reguläre Ausdrücke für eine einfache DOS-Attacke
ausnutzt, und warum ein Schutz davor immer die Spezifikation verletzt.

Der Zuhörer wird auch lernen, weshalb die Situation bei JSON-Schema
noch schwieriger ist als beim älteren XML-Standard. Denn
XML-Schema-Bibliotheken sind größtenteils anfällig für dieselbe
Attacke, aber nur deshalb, weil sie von der W3C-Spezifikation
abweichen.

== Der Redner

**Peter Liske** is a Senior Software Engineer at Zalando.
He studied Computer Science, Mathematics, and Physics
in Berlin and went through all stages of software
development – from system administrator to scrum master,
from developer to architect.
Peter's current favorite topics are web security, family
management, and sustainable agile work culture.

== Treffpunkt

codecentric AG, Köpenicker Str 31, 10179 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.


