= OpenJDK at Alibaba
Oliver B. Fischer
2018-03-23 20:03:00 +0100
:jbake-event-date: 2018-04-10
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published


Am **Dienstag, den 10. April 2018** lädt die
Java Usergroup Berlin-Brandenburg zusammen mit der
https://www.akelius.de/[Akelius GmbH^] zum Vortrag
**OpenJDK at Alibaba** mit Sanhong Li und Kingsum Chow von
http://www.alibabagroup.com/[Alibaba Inc.] ein.
This talk wil be held in English.

== Der Vortrag

**OpenJDK at Alibaba**
(_Kingsum Chow_, _Sanhong Li_):
On Nov 11, 2017, Alibaba smashed its own online transaction record once
again, the peak number of transactions per second reached to 325,000,
85% above last year’s 175,000.

Most of all the application in Alibaba are written in Java, with more
than billion lines of Java code. We already built and deployed
customized OpenJDK with our specific changes for large-scale
eCommerce web applications, which are running on more than 100,000
servers. In this talk, we will discuss how we tailor the OpenJDK for
our needs and, we will go into the details of the improvements we
made based on OpenJDK.

== Die Redner

**Kingsum Chow** is the systems software hardware co-optimization chief
scientist at Alibaba. He has over 15 years of optimizing Java
performance in collaboration with Appeal, IBM, BEA, Sun and Oracle
JVM teams while working at Intel. In 2016, he joined Alibaba to
improve Java performance through software hardware co-optimization.
Kingsum has been issued more than 20 patents. He also has delivered
more than 90 papers and presentations. Kingsum appeared three times in
JavaOne keynotes and almost a dozen times in JavaOne and Oracle
OpenWorld presentations covering the topic of software performance
systems and optimization. Kingsum received a PhD in Computer
Science and Engineering from the University of Washington in
Seattle in 1996.


**Sanhong Li** is JVM lead at Alibaba. He has been working on Java
since 2004, where he began at Intel Asia-Pacific R&D Lab implementing
JSR135. He joined IBM in 2008 to improve runtime security on OSGi platform.
He progressed to working on the development of IBM's Java Virtual Machine
in 2010, where he led a project to develop multi-tenancy technology for the
JVM. In 2014, he joined in Alibaba to lead the development for Alibaba JDK,
a customized OpenJDK version. Sanhong Li has presented at local and
international conferences such as JVM language summit, JavaOne and QCon.
He co-leads Shanghai Java User Group and co-chairs APMCon. He has authored
over 10 technical papers and a number of technical patents.


== Treffpunkt

Akelius GmbH, Erkelenzdamm 11-13,10999 Berlin, Germany


== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.

