= Spring Framework 5.1 on JDK 8 and 11
Oliver B. Fischer
2018-10-07 21:31:00 +0100
:jbake-event-date: 2018-11-01
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **Donnerstag, den 1. November 2018**, lädt die
Java Usergroup Berlin-Brandenburg
zum Vortrag
**Spring Framework 5.1 on JDK 8 and 11**
mit Jürgen Höller von
https://www.pivotal.io/[Pivotal^] ein.

== Der Vortrag

**Spring Framework 5.1 on JDK 8 and 11**
(_Jürgen Höller_):
Spring Framework 5.1 refines Spring’s functional and reactive API
style on a JDK 8 baseline and embraces JDK 11 for a smooth upgrade
to the next long-term support generation of the JVM. This talk illustrates
the benefits of a JDK 8 baseline and the compatibility challenges on JDK 11,
 providing upgrade advice for Spring applications on the classpath
 and the module path.

== Der Redner

**Jürgen Höller**
ist Mitbegründer des Open-Source-Projekts Spring Framework und begleitet
das Kernprojekt bereits seit 2003 als Projektleiter und Releasemanager.
Er ist ein erfahrener Softwarearchitekt und Berater mit besonderer
Expertise in Codeorganisation, Transaktionsmanagement und Messaging
in Unternehmensanwendungen.


== Treffpunkt

innoQ Deutschland GmbH, Ohlauer Str. 43, Treppenhaus C, 2. OG, 10999 Berlin

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.


