= Going Fullstack
Oliver B. Fischer
2019-03-23 16:26:00 +0100
:jbake-event-date: 2019-05-15
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published

Am **Mittwoch, den 15. Mai 2019** lädt die
Java Usergroup Berlin-Brandenburg
// zusammen mit der
// https://www.europace.de/[Europace AG^]
zum Vortrag
**Going Fullstack**
mit
Serafima Gurevich
// https://paluch.biz/[Mark Paluch^]
ein.

_**The talk will be held in English.**_

== Der Vortrag

**Going Fullstack**

(_Serafima Gurevich_):
For many years backend and frontend development felt like two completely
different worlds. However, a lot of change took place on both sides and
many bridges were built, bringing them surprisingly close to each other
and making the step to the other side not only easier but also fun.

The target group for this talk are backend Java developers with no
or little web UI knowledge.

The goal of this talk is to show the way towards frontend development
for Java backend developers, using the speaker's own backend to
fullstack journey as an example.

The talk will cover some general concepts in web UI development and
introduce some common tools and frameworks. Furthermore, we will talk
about testing as well as the integration of the UI development into
the continuous integration (CI) environment.


== Die Rednerin

**Serafima Gurevich** is a fullstack developer. She started her
career as a backend Java developer and dived into web UI
development along the way. Thus, this talk will contain
first-hand experiences and insights regarding
approaching this topic.



== Treffpunkt

TDB

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.




