= ModuleDiffer – API Brüche im Java Bytecode erkennen
Oliver B. Fischer
2019-10-04 23:39:00 +0100
:jbake-event-date: 2019-10-30
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published



Am **Mittwoch, den 30. Oktober 2019** lädt die
Java Usergroup Berlin-Brandenburg
und https://www.lucanet.com/de/[LucaNet AG^]
zum Vortrag
**ModuleDiffer – API Brüche im Java Bytecode erkennen**
mit
Philip Schmiel
ein.

== Der Vortrag

**ModuleDiffer – API Brüche im Java Bytecode erkennen**
(_Philip Schmiel_):
Auf dem Weg zur Modularisierung von großen Softwaremonolithen lauert die
Dependency Hell. Ein Weg ihr entgegenzuwirken ist die von Tom Preston-Werner
zusammengetragene Semantische Versionierung. Für einen Entwickler ist es aber
nicht immer eine einfache Entscheidung, ob eine bestimmte Änderung im Code einen
Bruch der API zur Folge hat.

Aus diesem Grund wurde bei LucaNet ein Werkzeug entwickelt, das anhand von Java
Bytecode API-Brechende Änderungen erkennen kann. Dieser Vortrag geht auf
Besonderheiten und interessante Randfälle in der JVM und dem Java Bytecode ein,
auf die wir während der Entwicklung dieses Werkzeuges gestoßen sind.

== Der Redner

**Philip Schmiel** ist Java Developer bei der LucaNet AG und entwirft
dort zusammen mit seinem Team einen Plugin-Mechanismus für die LucaNet Software.
Übersetzerbau ist seine Leidenschaft und er erweiterte für seine Bachelor-Arbeit
eine While-Sprache um Objektorientierung mit Möglichkeit zur Reflektion.


== Treffpunkt

LucaNet AG, Alexanderplatz 1, 10178 Berlin, Germany

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.





