= Reactive Relational Database Connectivity
Oliver B. Fischer
2019-02-16 10:29:00 +0100
:jbake-event-date: 2019-04-24
:jbake-type: post
:jbake-tags: treffen
:jbake-status: published



Am **Mittwoch, den 24. April 2019** lädt die
Java Usergroup Berlin-Brandenburg
// zusammen mit der
// https://www.europace.de/[Europace AG^]
zum Vortrag
**Reactive Relational Database Connectivity**
mit
https://paluch.biz/[Mark Paluch^]
ein.

_**The talk will be held in German.**_

== Der Vortrag

**Reactive Relational Database Connectivity**

(_Mark Paluch_):
Immer mehr Projekte setzen auf reaktive Programmierung. Auf ihrem
Weg reaktive Systeme zu bauen, stellen Entwicklungsteams fest,
dass sich sämtliche Vorteile dieser Umstellung nur bei einem
durchgängig reaktiven Stack einstellen.
Es gibt einige reaktive Messaging und NoSQL Integrationen,
jedoch gehören die relationalen Datenbanksysteme nicht dazu.

Dieser Vortrag stellt die Reactive Relational Database Connectivity
(R2DBC) Initiative vor. Das Ziel dieses Projekts ist es, ein
reaktives API für relationale Datenbanken zu definieren. Dieser
Vortrag erklärt das R2DBC API, seine Funktionsweise und die
Vorteile die sich aus der Nutzung ergeben. Wir schauen uns
auch Gemeinsamkeiten und Unterschiede weiterer Initiativen
wie ADBA, dem asynchronen Nachfolger von JDBC, an und wie
diese sich mit R2DBC nutzen lassen.

== Der Redner

**Mark Paluch** ist Software Craftsman und arbeitet als Spring Data
Engineer bei Pivotal. Er betreut die Module MongoDB, Redis und
Apache Cassandra und Entwickelt den Lettuce Redis Treiber.
Sein Fokus liegt derzeit auf reaktiven Treibern und
Infrastrukturkomponenten.

== Treffpunkt

idealo internet GmbH, Ritterstraße 11, 10969 Berlin, Deutschland

== Der Ablauf

- 18:30 Uhr Einlaß
- 19:00 Uhr Beginn des Vortrags

Anschließend gibt es die Möglichkeit für Networking und Plausch.

== Die Anmeldung

Über eine Voranmeldung zu der Veranstaltung über die
http://meetup.com/jug-bb/[Meetup-Gruppe
der JUG Berlin-Brandenburg^]
würden wir uns freuen, jedoch ist die Anmeldung nicht zwingend
erforderlich. Wir freuen uns auf jeden Teilnehmer.




