name: Run Gradle on PRs
on: push
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: bake
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: build/output
    - uses: actions/checkout@v2
      with:
        repository: jugbb/jugbb.github.io
        path: webpage
    - run: |
        ls -lha
        rsync -t -a -r -v build/output/* webpage
